"""Fail-closed person-month empirical-power engine for DAX Gate 1.

The only outcome input is the sealed pre-event CPS extract.  The loader first
reads YEAR, MONTH, and AGE, and refuses the file unless every row is ages 22--25
and dated 2021-11 through 2023-02.  Outcome columns are read only after that
check succeeds.  Post-event person-months copy the observed *design* of rotated
pre-event donor months; their outcomes are generated by an occupation-level
wild-cluster bootstrap and injected effects.  No post-event outcome file is an
argument to this program.

The real run additionally requires W5's balanced occupation-month dose panel.
If that file is absent, ``--emit-pending-if-dose-missing`` writes a sanitized
pending receipt and exits nonzero.  A sparse entrant companion, an
occupation-month cell table, or a synthetic dose panel is not an accepted
substitute.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import pathlib
from dataclasses import dataclass

import numpy as np


FIRST_EVENT = 202303
PRE_START = 202111
PRE_END = 202302
DOSE_SCALE = 0.10
Z_ALPHA_TWO_SIDED = 1.959963984540054
EMPLOYMENT_EFFECT_GRID = (-0.13, -0.10, -0.065, -0.04, -0.02, 0.0,
                          0.02, 0.04, 0.065, 0.10, 0.13)
HOURS_EFFECT_GRID = (-4.0, -3.0, -2.0, -1.0, -0.5, 0.0,
                     0.5, 1.0, 2.0, 3.0, 4.0)
SAFE_SEAL_COLUMNS = ("YEAR", "MONTH", "AGE")
REQUIRED_CPS_COLUMNS = {
    "YEAR", "MONTH", "ASECFLAG", "MISH", "WTFINL", "CPSIDP", "AGE",
    "SEX", "RACE", "HISPAN", "EMPSTAT", "OCC2010", "IND1990",
    "UHRSWORKT", "EDUC",
}
REQUIRED_DOSE_COLUMNS = {
    "cps_occ", "month", "dax", "industry", "static_decile", "weight",
}
FORBIDDEN_DOSE_TOKENS = {
    "employment", "hours", "wage", "earnings", "outcome", "empstat",
    "uhrsworkt", "payroll",
}
REGISTERED_CONTROL_FIELDS = ("AGE", "SEX", "RACE", "HISPAN", "EDUC", "MISH")


def sha256(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def month_code(year, month) -> np.ndarray:
    return np.asarray(year, dtype=np.int64) * 100 + np.asarray(month, dtype=np.int64)


def month_sequence(first: int, last: int) -> list[int]:
    year, month = divmod(first, 100)
    values = []
    while year * 100 + month <= last:
        values.append(year * 100 + month)
        month += 1
        if month == 13:
            year, month = year + 1, 1
    return values


def _safe_extract_manifest(path: pathlib.Path) -> dict[str, object]:
    """Inspect only non-outcome columns and enforce the pre-event seal."""
    import pyarrow.parquet as pq

    parquet = pq.ParquetFile(path)
    available = set(parquet.schema.names)
    missing = set(SAFE_SEAL_COLUMNS) - available
    if missing:
        raise ValueError(f"CPS extract lacks seal columns {sorted(missing)}")
    safe = pq.read_table(path, columns=list(SAFE_SEAL_COLUMNS)).to_pandas()
    ym = month_code(safe["YEAR"], safe["MONTH"])
    observed_months = sorted(np.unique(ym).tolist())
    expected_months = month_sequence(PRE_START, PRE_END)
    if observed_months != expected_months:
        raise ValueError(
            "REFUSED before reading outcomes: CPS extract must contain exactly "
            f"2021-11 through 2023-02; found {observed_months[:2]}..."
        )
    ages = set(safe["AGE"].astype(int).unique())
    if not ages or not ages <= {22, 23, 24, 25}:
        raise ValueError(
            "REFUSED before reading outcomes: CPS ages must be restricted to 22--25"
        )
    if np.any(ym >= FIRST_EVENT):
        raise ValueError("REFUSED before reading outcomes: post-event CPS rows detected")
    return {
        "rows": int(len(safe)),
        "start_month": "2021-11",
        "end_month": "2023-02",
        "age_min": int(min(ages)),
        "age_max": int(max(ages)),
        "post_event_rows": 0,
    }


def read_pre_event_extract(path: pathlib.Path):
    """Read outcomes only after a safe-column scan proves the file is pre-event."""
    import pyarrow.parquet as pq

    manifest = _safe_extract_manifest(path)
    available = set(pq.ParquetFile(path).schema.names)
    missing = REQUIRED_CPS_COLUMNS - available
    if missing:
        raise ValueError(f"CPS extract lacks required columns {sorted(missing)}")
    frame = pq.read_table(path, columns=sorted(REQUIRED_CPS_COLUMNS)).to_pandas()
    return frame, manifest


def canonical_occ(values):
    import pandas as pd

    numeric = pd.to_numeric(values, errors="raise")
    if numeric.isna().any() or np.any(numeric != np.floor(numeric)):
        raise ValueError("cps_occ must contain integer OCC2010 codes")
    return numeric.astype(np.int64).astype(str)


def validate_w5_dose_panel(frame):
    """Validate and normalize the executable W5 handoff contract."""
    import pandas as pd

    lower = {str(column).lower() for column in frame.columns}
    forbidden = sorted(
        column for column in lower
        if any(token in column for token in FORBIDDEN_DOSE_TOKENS)
    )
    if forbidden:
        raise ValueError(f"outcome-like columns forbidden in W5 dose panel: {forbidden}")
    missing = REQUIRED_DOSE_COLUMNS - set(frame.columns)
    if missing:
        raise ValueError(f"W5 dose panel lacks required columns {sorted(missing)}")

    data = frame.copy()
    data["cps_occ"] = canonical_occ(data["cps_occ"])
    parsed = pd.to_datetime(data["month"], errors="raise")
    if not (parsed.dt.day == 1).all():
        raise ValueError("W5 month must be the first day of each calendar month")
    data["month"] = parsed.dt.to_period("M").astype(str)
    data["month_code"] = parsed.dt.year * 100 + parsed.dt.month
    if data.duplicated(["cps_occ", "month"]).any():
        raise ValueError("W5 dose panel must have one row per occupation-month")
    if data[list(REQUIRED_DOSE_COLUMNS)].isna().any().any():
        raise ValueError("W5 required columns must be complete")
    data["dax"] = pd.to_numeric(data["dax"], errors="raise")
    if not data["dax"].between(0.0, 1.0).all():
        raise ValueError("W5 dax must lie in [0,1]")
    data["weight"] = pd.to_numeric(data["weight"], errors="raise")
    if not (data["weight"] > 0).all():
        raise ValueError("W5 weight must be strictly positive")
    data["static_decile"] = pd.to_numeric(data["static_decile"], errors="raise")
    if not data["static_decile"].between(1, 10).all():
        raise ValueError("W5 static_decile must lie in 1..10")
    if data.groupby("cps_occ")["static_decile"].nunique().max() != 1:
        raise ValueError("W5 static_decile must be frozen within occupation")

    months_by_occ = (data.sort_values(["cps_occ", "month_code"])
                     .groupby("cps_occ")["month_code"].apply(tuple))
    if len(months_by_occ) < 2 or months_by_occ.nunique() != 1:
        raise ValueError("W5 dose panel must be balanced over at least two occupations")
    months = sorted(data["month_code"].unique().tolist())
    if months != month_sequence(months[0], months[-1]):
        raise ValueError("W5 dose panel months must be contiguous")
    if months[0] > PRE_START or months[-1] < FIRST_EVENT:
        raise ValueError("W5 dose panel must span the pre-period and post-event months")
    if float(data.loc[data["month_code"] >= FIRST_EVENT, "dax"].var()) == 0.0:
        raise ValueError("W5 post-event dax has no variation")
    return data.sort_values(["cps_occ", "month_code"]).reset_index(drop=True)


def assign_reference_occupation(frame, maximum_lookback_months: int = 15):
    """Most recent valid occupation strictly before t, within 15 months."""
    import pandas as pd

    data = frame.copy()
    data["_month_index"] = data["YEAR"].astype(int) * 12 + data["MONTH"].astype(int) - 1
    data["reference_occ"] = np.nan
    valid = data["OCC2010"].between(1, 9899)
    for _, positions in data.groupby("CPSIDP", sort=False).groups.items():
        ordered = sorted(positions, key=lambda position: (data.at[position, "_month_index"], position))
        last_occ, last_month = None, None
        cursor = 0
        while cursor < len(ordered):
            current_month = data.at[ordered[cursor], "_month_index"]
            same_month = []
            while cursor < len(ordered) and data.at[ordered[cursor], "_month_index"] == current_month:
                same_month.append(ordered[cursor])
                cursor += 1
            if last_occ is not None and current_month - last_month <= maximum_lookback_months:
                data.loc[same_month, "reference_occ"] = last_occ
            valid_same_month = [position for position in same_month if bool(valid.at[position])]
            if valid_same_month:
                last_occ = int(data.at[valid_same_month[-1], "OCC2010"])
                last_month = int(current_month)
    return data.drop(columns="_month_index")


def prepare_person_records(frame):
    data = assign_reference_occupation(frame)
    data = data.loc[data["reference_occ"].notna() & (data["WTFINL"] > 0)].copy()
    data["cps_occ"] = data["reference_occ"].astype(np.int64).astype(str)
    data["month_code"] = month_code(data["YEAR"], data["MONTH"])
    data["month"] = (data["YEAR"].astype(int).astype(str) + "-" +
                     data["MONTH"].astype(int).astype(str).str.zfill(2))
    data["employment"] = data["EMPSTAT"].between(10, 19).astype(float)
    valid_hours = data["UHRSWORKT"].between(0, 168)
    data["hours_unconditional"] = np.where(
        data["employment"] == 0.0,
        0.0,
        np.where(valid_hours, data["UHRSWORKT"], np.nan),
    ).astype(float)
    return data


def build_person_panel(pre_records, doses):
    """Observed pre rows plus post rows using rotated pre-period donor designs."""
    import pandas as pd

    pre = prepare_person_records(pre_records)
    dose_columns = ["cps_occ", "month", "month_code", "dax", "static_decile"]
    actual_pre = pre.merge(doses[dose_columns], on=["cps_occ", "month", "month_code"],
                           how="left", validate="many_to_one")
    if actual_pre["dax"].isna().any():
        missing = int(actual_pre["dax"].isna().sum())
        raise ValueError(f"W5 dose panel does not cover {missing} eligible pre person-months")
    actual_pre["source"] = "observed_pre_design_and_outcome"

    donor_months = sorted(actual_pre["month_code"].unique().tolist())
    post_months = sorted(doses.loc[doses["month_code"] >= FIRST_EVENT, "month_code"].unique())
    post_parts = []
    for index, target in enumerate(post_months):
        donor_month = donor_months[index % len(donor_months)]
        donor = actual_pre.loc[actual_pre["month_code"] == donor_month,
                               list(pre.columns)].copy()
        donor["YEAR"] = target // 100
        donor["MONTH"] = target % 100
        donor["month_code"] = target
        donor["month"] = f"{target // 100:04d}-{target % 100:02d}"
        donor = donor.merge(doses[dose_columns], on=["cps_occ", "month", "month_code"],
                            how="left", validate="many_to_one")
        if donor["dax"].isna().any():
            raise ValueError(f"W5 dose panel does not cover donor occupations in {target}")
        donor["source"] = "simulated_post_from_pre_design"
        post_parts.append(donor)
    if not post_parts:
        raise ValueError("W5 dose panel supplies no post-event design months")
    return pd.concat([actual_pre, *post_parts], ignore_index=True)


class WeightedAbsorber:
    """Alternating weighted projections for additive categorical effects."""

    def __init__(self, categories: list[np.ndarray], weights: np.ndarray,
                 tolerance: float = 1e-10, maximum_iterations: int = 500):
        self.weights = np.asarray(weights, dtype=float)
        if np.any(self.weights <= 0):
            raise ValueError("person weights must be strictly positive")
        self.codes = []
        for values in categories:
            _, inverse = np.unique(np.asarray(values).astype(str), return_inverse=True)
            self.codes.append(inverse)
        self.tolerance = tolerance
        self.maximum_iterations = maximum_iterations

    def residualize(self, values: np.ndarray) -> np.ndarray:
        result = np.asarray(values, dtype=float).copy()
        was_vector = result.ndim == 1
        if was_vector:
            result = result[:, None]
        for _ in range(self.maximum_iterations):
            before = result.copy()
            for code in self.codes:
                denominator = np.bincount(code, weights=self.weights)
                for column in range(result.shape[1]):
                    numerator = np.bincount(
                        code, weights=self.weights * result[:, column],
                        minlength=len(denominator),
                    )
                    result[:, column] -= (numerator / denominator)[code]
            if float(np.max(np.abs(result - before))) < self.tolerance:
                break
        else:
            raise RuntimeError("fixed-effect absorber did not converge")
        return result[:, 0] if was_vector else result


@dataclass
class Fit:
    beta: float
    standard_error: float
    residual: np.ndarray
    y_residual: np.ndarray


class OccupationClusterEstimator:
    def __init__(self, x, weights, clusters, absorber: WeightedAbsorber):
        self.x = np.asarray(x, dtype=float)
        self.weights = np.asarray(weights, dtype=float)
        self.clusters = np.asarray(clusters).astype(str)
        _, self.cluster_code = np.unique(self.clusters, return_inverse=True)
        self.n_clusters = int(self.cluster_code.max() + 1)
        if self.n_clusters < 2:
            raise ValueError("occupation-clustered inference needs at least two clusters")
        self.absorber = absorber
        self.x_residual = absorber.residualize(self.x)
        self.denominator = float(np.dot(self.weights * self.x_residual, self.x_residual))
        if self.denominator <= 1e-12:
            raise ValueError("DAX has no residual identifying variation after controls")

    def fit(self, y) -> Fit:
        y_residual = self.absorber.residualize(np.asarray(y, dtype=float))
        beta = float(np.dot(self.weights * self.x_residual, y_residual) / self.denominator)
        residual = y_residual - beta * self.x_residual
        scores = np.bincount(
            self.cluster_code,
            weights=self.weights * self.x_residual * residual,
            minlength=self.n_clusters,
        )
        variance = ((self.n_clusters / (self.n_clusters - 1)) *
                    float(np.dot(scores, scores)) / self.denominator ** 2)
        return Fit(beta, float(np.sqrt(max(variance, 0.0))), residual, y_residual)


def build_estimator(panel):
    month = panel["month"].astype(str).to_numpy()
    categories = [
        panel["cps_occ"].astype(str).to_numpy(),
        month,
        (panel["IND1990"].astype(str) + "|" + panel["month"].astype(str)).to_numpy(),
        (panel["static_decile"].astype(str) + "|" + panel["month"].astype(str)).to_numpy(),
        *[panel[field].astype(str).to_numpy() for field in REGISTERED_CONTROL_FIELDS],
    ]
    weights = panel["WTFINL"].astype(float).to_numpy()
    absorber = WeightedAbsorber(categories, weights)
    return OccupationClusterEstimator(
        panel["dax"].astype(float).to_numpy() / DOSE_SCALE,
        weights,
        panel["cps_occ"].astype(str).to_numpy(),
        absorber,
    )


def simulate_outcome(estimator: OccupationClusterEstimator, baseline, effects,
                     reps: int, seed: int) -> dict[str, object]:
    base_fit = estimator.fit(baseline)
    nuisance_fitted = np.asarray(baseline, dtype=float) - base_fit.y_residual
    rng = np.random.default_rng(seed)
    null_beta, standard_errors = [], []
    for _ in range(reps):
        multiplier = rng.choice((-1.0, 1.0), size=estimator.n_clusters)
        simulated_null = nuisance_fitted + multiplier[estimator.cluster_code] * base_fit.residual
        fit = estimator.fit(simulated_null)
        null_beta.append(fit.beta)
        standard_errors.append(fit.standard_error)
    null_beta = np.asarray(null_beta)
    standard_errors = np.asarray(standard_errors)
    safe_se = np.maximum(standard_errors, 1e-12)
    rejection = {
        f"{effect:g}": round(float(np.mean(
            np.abs((null_beta + effect) / safe_se) > Z_ALPHA_TWO_SIDED
        )), 4)
        for effect in effects
    }
    powered = [abs(effect) for effect in effects
               if effect != 0 and rejection[f"{effect:g}"] >= 0.80]
    return {
        "median_cr1_standard_error": round(float(np.median(standard_errors)), 8),
        "analytic_mde80": round(float(2.80 * np.median(standard_errors)), 8),
        "empirical_grid_mde80": min(powered) if powered else None,
        "rejection_rate_by_effect": rejection,
    }


def judge(report: dict[str, object], standard: dict[str, object]) -> None:
    frozen = (standard.get("status") == "FROZEN" and
              standard.get("benchmark", {}).get("locator_status") == "VERIFIED")
    for outcome, ceiling_key in (("employment", "employment_mde_ceiling"),
                                 ("hours_unconditional", "hours_mde_ceiling")):
        ceiling = standard.get("standard", {}).get(ceiling_key)
        report[outcome]["approved_mde_ceiling"] = ceiling
        report[outcome]["adequately_powered"] = (
            report[outcome]["analytic_mde80"] <= ceiling
            if frozen and ceiling is not None else None
        )
    report["gate_1_pass"] = bool(
        frozen and report["employment"]["adequately_powered"]
        and report["hours_unconditional"]["adequately_powered"]
    )
    report["status"] = (
        "PASS_PERSON_LEVEL_POWER" if report["gate_1_pass"]
        else "PERSON_LEVEL_POWER_COMPLETE_GATE_BLOCKED"
    )


def run(cps_path: pathlib.Path, dose_path: pathlib.Path, output: pathlib.Path,
        standard_path: pathlib.Path, reps: int, seed: int) -> dict[str, object]:
    import pandas as pd

    pre, pre_manifest = read_pre_event_extract(cps_path)
    dose_frame = (pd.read_parquet(dose_path) if dose_path.suffix == ".parquet"
                  else pd.read_csv(dose_path))
    doses = validate_w5_dose_panel(dose_frame)
    panel = build_person_panel(pre, doses)
    estimator = build_estimator(panel)
    hours_panel = panel.loc[panel["hours_unconditional"].notna()].copy()
    hours_estimator = build_estimator(hours_panel)
    report = {
        "status": "PERSON_LEVEL_POWER_RUNNING",
        "gate_1_pass": False,
        "unit": "person-month",
        "estimand": "change in outcome per 0.10 increase in monthly DAX",
        "outcomes": ["employment indicator", "unconditional weekly hours"],
        "post_event_outcomes": "simulated; no real post-event outcomes read",
        "simulation": "Rademacher wild cluster bootstrap on pre-outcome residuals",
        "reps": reps,
        "seeds": {"employment": seed, "hours_unconditional": seed + 1},
        "alpha_two_sided": 0.05,
        "rejection_rule": "abs(beta_hat / CR1 occupation-clustered SE) > 1.959963984540054",
        "cluster": "original CPS OCC2010 reference occupation",
        "controls": [
            "occupation FE", "calendar-month FE", "industry-by-month FE",
            "frozen static-exposure-decile-by-month FE",
            *[f"categorical {field}" for field in REGISTERED_CONTROL_FIELDS],
        ],
        "effect_grids": {
            "employment": list(EMPLOYMENT_EFFECT_GRID),
            "hours_unconditional": list(HOURS_EFFECT_GRID),
        },
        "inputs": {
            "cps_extract_name": cps_path.name,
            "cps_extract_sha256": sha256(cps_path),
            "cps_safe_manifest": pre_manifest,
            "w5_dose_panel_name": dose_path.name,
            "w5_dose_panel_sha256": sha256(dose_path),
        },
        "n_person_months": int(len(panel)),
        "n_person_months_by_outcome": {
            "employment": int(len(panel)),
            "hours_unconditional": int(len(hours_panel)),
        },
        "n_occupation_clusters_by_outcome": {
            "employment": estimator.n_clusters,
            "hours_unconditional": hours_estimator.n_clusters,
        },
        "employment": simulate_outcome(
            estimator, panel["employment"].to_numpy(), EMPLOYMENT_EFFECT_GRID,
            reps, seed,
        ),
        "hours_unconditional": simulate_outcome(
            hours_estimator, hours_panel["hours_unconditional"].to_numpy(), HOURS_EFFECT_GRID,
            reps, seed + 1,
        ),
        "failure_conditions": [
            "any post-event row in the CPS outcome extract",
            "missing, unbalanced, noncontiguous, or outcome-bearing W5 dose panel",
            "fewer than two occupation clusters",
            "no residual DAX variation after registered controls",
            "unverified or unfrozen external benchmark",
        ],
    }
    standard = json.loads(standard_path.read_text(encoding="utf-8"))
    judge(report, standard)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    return report


def emit_pending(cps_path: pathlib.Path, dose_path: pathlib.Path,
                 output: pathlib.Path, standard_path: pathlib.Path,
                 reps: int, seed: int) -> dict[str, object]:
    manifest = _safe_extract_manifest(cps_path)
    standard = json.loads(standard_path.read_text(encoding="utf-8"))
    report = {
        "status": "PENDING_W5_DOSE_PANEL",
        "gate_1_pass": False,
        "unit": "person-month",
        "cps_pre_event_contract": manifest,
        "cps_extract_name": cps_path.name,
        "w5_dose_panel_name": dose_path.name,
        "w5_dose_panel_present": False,
        "benchmark_value": standard.get("benchmark", {}).get("relative_decline"),
        "benchmark_version_status": standard.get("benchmark", {}).get("version_status"),
        "reps_planned": reps,
        "seeds_planned": {"employment": seed, "hours_unconditional": seed + 1},
        "effect_grids": {
            "employment": list(EMPLOYMENT_EFFECT_GRID),
            "hours_unconditional": list(HOURS_EFFECT_GRID),
        },
        "pending_dependencies": [
            "real frozen W5 balanced occupation-month dose panel",
            "verified exact locator for the PI-selected power benchmark",
        ],
        "substitutes_explicitly_rejected": [
            "sparse entrant companion", "occupation-month cell arithmetic",
            "synthetic dose panel",
        ],
        "post_event_outcomes_read": False,
        "generated_at_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    return report


def main() -> int:
    here = pathlib.Path(__file__).resolve().parent
    parser = argparse.ArgumentParser()
    parser.add_argument("--cps-extract", type=pathlib.Path, required=True)
    parser.add_argument("--dose-panel", type=pathlib.Path, required=True)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    parser.add_argument("--standard", type=pathlib.Path,
                        default=here / "power_standard.json")
    parser.add_argument("--reps", type=int, default=999)
    parser.add_argument("--seed", type=int, default=20260819)
    parser.add_argument("--emit-pending-if-dose-missing", action="store_true")
    args = parser.parse_args()
    if args.reps < 19:
        raise SystemExit("reps must be at least 19")
    if not args.dose_panel.is_file():
        if not args.emit_pending_if_dose_missing:
            raise SystemExit(f"W5 dose panel is missing: {args.dose_panel}")
        report = emit_pending(args.cps_extract, args.dose_panel, args.output,
                              args.standard, args.reps, args.seed)
        print(json.dumps(report, indent=2))
        return 2
    report = run(args.cps_extract, args.dose_panel, args.output,
                 args.standard, args.reps, args.seed)
    print(json.dumps(report, indent=2))
    return 0 if report["gate_1_pass"] else 2


if __name__ == "__main__":
    raise SystemExit(main())
