"""P1 — generate the four post-gate extraction batch specs from the harvested
EDGAR package (L0, deterministic, no LLM). RUN ON THE BOX — raw filings are
box-local (p1/edgar_filings/*.htm, gitignored; manifest.csv is committed).

Emits ops/l1/{P1-T1-events,P1-T1-events-B,P1-T13-ant,P1-T13-ant-B}.yaml:
  - T1 channels get filings matched by conversion-language queries;
    T13 channels get filings matched by ANT/semi-transparent queries.
  - Channel A worker = deepseek, channel B = gemini_free (kimi is benched;
    deepseek/google keeps the cross-vendor A/B constraint; extraction reads
    EMBEDDED text so neither channel needs web_search).
  - One item per filing: focused excerpts (keyword windows) rather than the
    whole prospectus; per manual §T1 every field must be locatable in the
    filing, NA otherwise, no memory.
  - Known-answer fence from repo-verified facts (docs 修订3 anchor date;
    P1-T0-crash-B owner-armed FEDS-note fence; events_from_note.csv family).

Idempotent: --force to overwrite existing specs.
"""
import argparse
import csv
import html
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PKG = os.path.join(ROOT, "p1", "edgar_filings")
L1 = os.path.join(ROOT, "ops", "l1")

ANT_MARKERS = ("activeshares", "semi-transparent", "proxy portfolio")
KEYWORDS = re.compile(r"convert|conversion|exchange-traded|semi-transparent|"
                      r"proxy portfolio|activeshares", re.I)
WINDOW, MAX_WINDOWS, HEAD = 1500, 4, 1200
TAG = re.compile(r"<[^>]+>")

T1_RULES = """【规则 (manual §T1 verbatim): 每个字段必须能在本文件节选中找到原文依据;
抽不到的字段填 NA, 不许推断; announce_date = 首次披露转换意向日期,
effective_date = 声明的生效日, 缺一降 confidence; 不得用记忆补充其他事件;
输出一行 JSON 对象, 字段: fund_name, family, mutual_fund_ticker, etf_ticker,
announce_date, effective_date, asset_class(equity_US/equity_intl/fixed_income/other),
AUM_at_conversion_USD, source_accession, source_url, confidence(H/M/L)。
若节选不含转换事件 → {"no_event": true} 。同一基金日期矛盾 → NEED_HUMAN 并引两处原文。】"""

T13_RULES = """【规则 (修订4 T13, schema 同 T1 增两列): disclosure_regime(daily_full/
semi_transparent), proxy_basket_type。逐字段定位符; NA 不推断; 不含相关事件 →
{"no_event": true}。范围: 2019-11 以来上市或转换的半透明主动 ETF。】"""

SENTINELS = """# Known-answer fence: repo-verified facts (docs/P1_修订补丁_v1_1.md 修订3;
# ops/l1/P1-T0-crash-B.yaml owner-armed fence; p1/events_from_note.csv).
sentinels:
  - id: S1
    prompt: "Which fund family completed the industry's largest mutual-fund-to-ETF conversion in June 2021? Reply with the family name only, one word."
    expect: "Dimensional"
  - id: S2
    prompt: "In which year and month was the Saglam-Tuzun FEDS Note on mutual-fund-to-ETF conversions published? Reply with YYYY-MM only, nothing else."
    expect: "2025-11"
  - id: S3
    prompt: "In which year and month did the Dimensional anchor-wave mutual-fund-to-ETF conversions become effective? Reply with YYYY-MM only, nothing else."
    expect: "2021-06"
"""


def excerpt(path):
    try:
        raw = io.open(path, "r", encoding="utf-8", errors="ignore").read()
    except IOError:
        return None
    text = html.unescape(TAG.sub(" ", raw))
    text = re.sub(r"\s+", " ", text).strip()
    if not text:
        return None
    parts, spans = [text[:HEAD]], []
    for m in KEYWORDS.finditer(text):
        lo, hi = max(0, m.start() - WINDOW // 2), m.start() + WINDOW
        if spans and lo <= spans[-1][1]:
            spans[-1] = (spans[-1][0], hi)
        else:
            spans.append((lo, hi))
        if len(spans) >= MAX_WINDOWS:
            break
    parts += [text[lo:hi] for lo, hi in spans if lo > HEAD]
    return " […] ".join(parts)


def yaml_quote_block(s):
    return "\n".join("      " + line for line in s.splitlines())


def build_spec(task_id, worker, rules, rows, channel_note):
    lines = [
        "# {0} — generated by p1/make_extraction_specs.py from the harvested".format(task_id),
        "# EDGAR package ({0} filings; manifest.csv is the locator source).".format(len(rows)),
        "# {0}".format(channel_note),
        "# Extraction reads embedded excerpts — no web_search needed.",
        "worker: {0}".format(worker),
        "web_search: false",
        "max_items_per_call: 6",
        "est_cost: {0}".format(round(0.01 * len(rows) + 0.5, 2)),
        "items:",
    ]
    for r in rows:
        body = "{0}\n文件: {1} (form {2}, filed {3}, {4})\nsource_url: {5}\n节选:\n{6}".format(
            rules, r["accession"], r["form"], r["filed"], r["company"],
            r["source_url"], r["_excerpt"])
        lines.append("  - id: \"{0}\"".format(r["accession"]))
        lines.append("    prompt: |")
        lines.append(yaml_quote_block(body))
    return "\n".join(lines) + "\n" + SENTINELS


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--max-per-task", type=int, default=0, help="cap items (smoke)")
    args = ap.parse_args()
    man = os.path.join(PKG, "manifest.csv")
    if not os.path.exists(man):
        sys.exit("NEED_INFO: manifest.csv missing — run p1/fetch_edgar_filings.py first")
    t1, t13, missing, seen = [], [], 0, set()
    with open(man) as f:
        for r in csv.DictReader(f):
            key = (r["cik"], r["accession"])
            if key in seen:
                continue
            seen.add(key)
            p = os.path.join(PKG, "{0}_{1}.htm".format(r["cik"], r["accession"]))
            ex = excerpt(p)
            if ex is None:
                missing += 1
                continue
            r["_excerpt"] = ex
            bucket = t13 if any(m in r["query_phrase"].lower() for m in ANT_MARKERS) else t1
            bucket.append(r)
    if args.max_per_task:
        t1, t13 = t1[:args.max_per_task], t13[:args.max_per_task]
    if missing:
        print("WARN: {0} manifest rows have no local .htm (download gaps) — "
              "re-run the harvester to fill".format(missing))
    if not t1 and not t13:
        sys.exit("NEED_INFO: no local filings readable — is this the box?")
    # K-4 guard (audit 2026-07-10): a manifest with implausibly few conversion-
    # family filings must not silently become P1-T1's event universe (the
    # hand-run manifest had 9 vs 401 T13-family). Dozens of managers converted
    # 2021-2026; anything under this floor means harvest phrase coverage or
    # truncation is broken — fix the harvest, don't spec.
    MIN_T1 = 40
    if 0 < len(t1) < MIN_T1 and not args.max_per_task and not args.force:
        print("K-4 GUARD: only {0} conversion-family filings (< {1}) — "
              "refusing to write P1-T1 specs from this manifest. Re-run the "
              "harvester with the expanded phrase family; --force only with "
              "an owner-reviewed justification.".format(len(t1), MIN_T1))
        t1 = []
    plans = [
        ("P1-T1-events", "deepseek", T1_RULES, t1,
         "Channel A. kimi benched -> deepseek; B channel is gemini (google) so cross-vendor holds."),
        ("P1-T1-events-B", "gemini_free", T1_RULES, t1,
         "Channel B (channel_of P1-T1-events), google family."),
        ("P1-T13-ant", "deepseek", T13_RULES, t13,
         "Channel A (ANT/semi-transparent subset)."),
        ("P1-T13-ant-B", "gemini_free", T13_RULES, t13,
         "Channel B, google family."),
    ]
    for task_id, worker, rules, rows, note in plans:
        if not rows:
            print("{0}: 0 filings in scope — spec not written".format(task_id))
            continue
        dest = os.path.join(L1, task_id + ".yaml")
        if os.path.exists(dest) and not args.force:
            print("{0}: exists, skipping (--force to overwrite)".format(task_id))
            continue
        with io.open(dest, "w", encoding="utf-8") as f:
            f.write(build_spec(task_id, worker, rules, rows, note))
        print("{0}: wrote {1} items -> {2}".format(task_id, len(rows), dest))


if __name__ == "__main__":
    main()
